pipeline {
     agent any
    tools {
        maven 'Maven  3.9.71'
        jdk 'Java 17.0.11'
    }
    stages {
       
       stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                 '''
            }
        }
       
       
    }
}