pipeline {
     agent any
   
    stages {
       
       stage ('Initialize') {
            steps {
                sh '''
                   export M2_HOME=/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn3_9_7 >> ~/.bashrc
                   export PATH=${M2_HOME}/bin:${PATH} >> ~/.bashrc
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                 '''
            }
        }
    
    
    stage('Build') { 
            steps {
                sh 'cd fintech-parent && ls' 
            }
        }   
       
    }
}