apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: fintech-parent
build:
  artifacts:
    - image: customer
      jib:
      # project can be the relative directory
       project: customer
    - image: fintech-web
      docker:
      # project can be the relative directory
       dockerfile: ./fintech-web/Dockerfile
      context: fintech-web
       
      # buildArgs:
       # -context: fintech-web
      #  -aa: ./fintech-web
    - image: fintech-config
      jib:
      # project can be the relative directory
       project: fintech-config
    - image: fintech-gateway
      jib:
      # project can be the relative directory
       project: fintech-gateway
   
    - image: notification
      jib:
      # project can be the relative directory
       project: notification
    - image: order
      jib:
      # project can be the relative directory
       project: order
    - image: product-recommendation
      jib:
      # project can be the relative directory
       project:  product-recommendation
    - image: product-review
      jib:
      # project can be the relative directory
       project: product-review
    - image: product-search
      jib:
      # project can be the relative directory
       project: product-search
    - image: product
      jib:
      # project can be the relative directory
       project: product
manifests:
  rawYaml:
    - customer/deployment.yaml
    - fintech-web/deployment.yaml
    - fintech-config/deployment.yaml
    - fintech-gateway/deployment.yaml
    - product/deployment.yaml
    - notification/deployment.yaml
    - order/deployment.yaml
    - product-recommendation/deployment.yaml
    - product-review/deployment.yaml
    - product-search/deployment.yaml
portForward:
- resourceType: Service
  resourceName: product
  namespace: default
  port: 8091
  localPort: 8091 # *Optional* 
- resourceType: Service
  resourceName: order
  namespace: default
  port: 8092
  localPort: 8092 # *Optional*
- resourceType: Service
  resourceName: kafkaui
  namespace: default
  port: 8071
  localPort: 8071 # *Optional*
- resourceType: Service
  resourceName: debezium-ui
  namespace: default
  port: 8074
  localPort: 8074 # *Optional*
- resourceType: Service
  resourceName: camunda-platform-tasklist
  namespace: default
  port: 80
  localPort: 70 # *Optional*
- resourceType: Service
  resourceName: camunda-platform-operate
  namespace: default
  port: 80
  localPort: 71 # *Optional*
- resourceType: Service
  resourceName: order-db
  namespace: default
  port: 3306
  localPort: 3306 # *Optional*
- resourceType: Service
  resourceName: product-db
  namespace: default
  port: 3309
  localPort: 3309 # *Optional*
- resourceType: Service
  resourceName: camunda-platform-zeebe-gateway
  namespace: default
  port: 26500 
  localPort: 26500 # *Optional*
  
- resourceType: Service
  resourceName: jaeger
  namespace: default
  port: 16686 
  localPort: 16686 # *Optional*

- resourceType: Service
  resourceName: connect
  namespace: default
  port: 8083 
  localPort: 8083 # *Optional*
# exposing kubernetes infrasture services to local environment 
- resourceType: Service
  resourceName: my-cluster-kafka-bootstrap
  namespace: default
  port: 9092 
  localPort: 9092 # *Optional*
  
  # exposing kubernetes infrasture services to local environment 
- resourceType: Service
  resourceName: order-db
  namespace: default
  port: 3306  
  localPort: 3306  # *Optional*
- resourceType: Service
  resourceName: polar-keycloak
  namespace: default
  port: 8090  
  localPort: 72  # *Optional*
- resourceType: Service
  resourceName: fintech-web
  namespace: default
  port: 3000  
  localPort: 3000  # *Optional*