global:
  scrape_interval: 2s

scrape_configs:
  
  - job_name: 'checkout-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'checkout:8080' ]    
  
  - job_name: 'order-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order:8082' ]   