apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  ports:
   - port: 8091
     targetPort: 8080  
     protocol: TCP
  selector:
    app: product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product
        env:
         - name : SPRING_DATASOURCE_URL
           value : jdbc:mysql://product-db:3309/product
