apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product
