apiVersion: v1
kind: Service
metadata:
  name: product-search
  labels:
    app: product-search
spec:
  ports:
  - port: 9098
    protocol: TCP
  clusterIP: None
  selector:
    app: product-search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search
  labels:
    app: product-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-search
  template:
    metadata:
      labels:
        app: product-search
    spec:
      containers:
      - name: product-search
        image: product-search
