apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: connect
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connect
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: connect
    spec:
      containers:
        - args:
            - /opt/kafka/kafka_connect_run.sh
          env:
            - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_CONNECT_CONFIGURATION
              value: |2
                key.converter=org.apache.kafka.connect.json.JsonConverter
                value.converter=org.apache.kafka.connect.json.JsonConverter
                key.converter.schemas.enable=false
                value.converter.schemas.enable=false
                group.id=connect
                offset.storage.topic=connect-offsets
                offset.storage.replication.factor=1
                config.storage.topic=connect-configs
                config.storage.replication.factor=1
                status.storage.topic=connect-status
                status.storage.replication.factor=1
                producer.interceptor.classes=io.debezium.tracing.DebeziumTracingProducerInterceptor
                otel.instrumentation.common.default-enabled=false
            - name: KAFKA_LOG4J_OPTS
              value: -Dlog4j.configuration=file:/opt/kafka/config/connect-log4j.properties
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4317
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_SERVICE_NAME
              value: kafka-connect
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_TRACES_SAMPLER
              value: always_on
            - name: STRIMZI_TRACING
              value: opentelemetry
          image: hossamaboelhassan/strimzi-connect
          name: connect
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
