apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: debezium-ui
  name: debezium-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: debezium-ui
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: debezium-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CONNECT_URIS
              value: http://connect:8083
          image: quay.io/debezium/debezium-ui:2.4
          name: debezium-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
