apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: password
            - name: GF_SECURITY_ADMIN_USER
              value: user
          image: grafana/grafana:9.1.2
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              name: grafana-cm0
              subPath: datasource.yml
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-cm1
            - mountPath: /etc/grafana/grafana.ini
              name: grafana-cm2
              subPath: grafana.ini
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: datasource.yml
                path: datasource.yml
            name: grafana-cm0
          name: grafana-cm0
        - configMap:
            name: grafana-cm1
          name: grafana-cm1
        - configMap:
            items:
              - key: grafana.ini
                path: grafana.ini
            name: grafana-cm2
          name: grafana-cm2
