apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafkaui
  name: kafkaui
spec:
  ports:
    - name: "8071"
      port: 8071
      targetPort: 8080
  selector:
    io.kompose.service: kafkaui
