apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: payment-db
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: payment-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: payment
            - name: MYSQL_PASSWORD
              value: payment_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: payment_user
          image: mysql:8.4.0
          name: payment-db
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
