apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: polar-keycloak
  name: polar-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: polar-keycloak
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: polar-keycloak
    spec:
      containers:
        - args:
            - start-dev
          env:
            - name: KEYCLOAK_ADMIN
              value: user
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: password
          image: quay.io/keycloak/keycloak:22.0.0
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
