apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: product-db
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-infra-final.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: product-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: product
            - name: MYSQL_PASSWORD
              value: product_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: product_user
          image: mysql:8.3.0
          name: product-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: productdb-data
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: productdb-data
