apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval: 2s\n\nscrape_configs:\n  \n  - job_name: 'checkout-service'\n    scrape_interval: 2s\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'checkout:8080' ]    \n  \n  - job_name: 'order-service'\n    scrape_interval: 2s\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'order:8082' ]   "
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
