annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "configurable update strategy"
    - kind: added
      description: "support dnsPolicy and dnsConfig for all components"
    - kind: added
      description: "add console auth vars"
    - kind: fixed
      description: "identity base url not configured"
    - kind: fixed
      description: "unauthenticated external elasticsearch no longer forces password…"
    - kind: changed
      description: "remove the global image tag value and use it from the components"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  camunda.io/helmCLIVersion: 3.15.2
  dummy: dummy
apiVersion: v2
appVersion: 8.5.x
dependencies:
- alias: identityKeycloak
  condition: identity.keycloak.enabled,identityKeycloak.enabled
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 19.4.1
- alias: identityPostgresql
  condition: identity.postgresql.enabled,identityPostgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
- alias: postgresql
  condition: postgresql.enabled
  name: web-modeler-postgresql
  repository: file://../web-modeler-postgresql
  version: 11.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.0.4
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
description: 'Camunda 8 Self-Managed Helm charts. Camunda''s process automation platform
  allows developers to design, automate and improve processes. '
home: https://docs.camunda.io/docs/self-managed/overview/
icon: https://helm.camunda.io/imgs/camunda.svg
keywords:
- bpm
- bpmn
- camunda-platform
- dmn
- process-engine
- workflow
maintainers:
- email: christopher.zell@camunda.com
  name: Zelldon
- email: ahmed.abouzaid@camunda.com
  name: aabouzaid
name: camunda-platform
sources:
- https://github.com/camunda/camunda-platform-helm
type: application
version: 10.2.0
