apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 8092
      targetPort: 8080
      protocol: TCP
  selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order
        env:
         - name : SPRING_DATASOURCE_URL
           value : jdbc:mysql://order-db:3306/order